### ISSUE TITLE
Metodo de arranque de la BD

### ISSUE THREAD

**Issue by ManuelMori** [Arquisoft/Loader_e5b#4]
La base de datos se inicia desde _startup.bat_ dentro de la carpeta _BD_ (heredado del otro grupo...). Dado que no iniciamos la base de datos con el programa las pruebas (de la plataforma de github) __fallan__. Seria conveniente encontrar la manera de __iniciar y detener la base de datos con el programa__, de tal forma que no sea necesario ejecutar ningun archivo externo.

**Comment by uo238688** [comment]
La base de datos ahora se inicia con Travis.
